export const EVENTS = {
  ORDER_CREATED: "ORDER_CREATED",
  ORDER_CONFIRMED: "ORDER_CONFIRMED",

  DRIVER_ASSIGNED: "DRIVER_ASSIGNED",

  PICKED_UP: "PICKED_UP",
  IN_TRANSIT: "IN_TRANSIT",
  DELIVERED: "DELIVERED",

  WAREHOUSE_UPDATED: "WAREHOUSE_UPDATED",

  PAYMENT_PENDING: "PAYMENT_PENDING",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",
} as const;